name: DoubleOK
favicon: null
layout_spectrum: 0.5376496824901551
typography_spectrum: 0.4652945715934038
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.32565247593447566
  lightness: 0.509568054927513
  saturation: 0.4133559330366552
  rhythmicContrast: 0.20142088690772653
purpose: []
